// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zzpcroisphonssrlwvcd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp6cGNyb2lzcGhvbnNzcmx3dmNkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI2Mzc5MDMsImV4cCI6MjA2ODIxMzkwM30.iGwrDlMKnHRsolDSizS6kERTeGB3HApKod2eOS0cwI0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});